-- Archivo: 01_crear_tablas.sql
-- Fecha: 2025/09/04
-- Nota: Usando tamaños razonables para VARCHAR2 Para nombres y ubicaciones con 100 chars debería bastar.

CREATE TABLE COMERCIANTES (
    ID NUMBER PRIMARY KEY,
    NOMBRE VARCHAR2(100) NOT NULL,
    DEPARTAMENTO VARCHAR2(100) NOT NULL,
    MUNICIPIO VARCHAR2(100) NOT NULL,
    TELEFONO VARCHAR2(20),
    CORREO VARCHAR2(100),
    FECHA_REGISTRO DATE NOT NULL,
    ESTADO VARCHAR2(20) NOT NULL CHECK (ESTADO IN ('ACTIVO', 'INACTIVO', 'SUSPENDIDO')),
    FECHA_ACTUALIZACION DATE,
    USUARIO_ACTUALIZACION VARCHAR2(50)
);

CREATE TABLE ESTABLECIMIENTOS (
    ID NUMBER PRIMARY KEY,
    COMERCIANTE_ID NUMBER NOT NULL,
    NOMBRE VARCHAR2(100) NOT NULL,
    INGRESOS NUMBER(15,2),
    NUM_EMPLEADOS NUMBER,
    FECHA_ACTUALIZACION DATE,
    USUARIO_ACTUALIZACION VARCHAR2(50),
    CONSTRAINT FK_COMERCIANTE FOREIGN KEY (COMERCIANTE_ID) REFERENCES COMERCIANTES(ID)
);
