-- Archivo: 02_secuencias_triggers.sql
-- Fecha: 2025/09/04

CREATE SEQUENCE SEQ_COMERCIANTES START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE SEQUENCE SEQ_ESTABLECIMIENTOS START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

-- Trigger para ID automático en COMERCIANTES
CREATE OR REPLACE TRIGGER TRG_COMERCIANTES_ID
BEFORE INSERT ON COMERCIANTES
FOR EACH ROW
BEGIN
    :NEW.ID := SEQ_COMERCIANTES.NEXTVAL;
END;
/

-- Trigger para ID automático en ESTABLECIMIENTOS
CREATE OR REPLACE TRIGGER TRG_ESTABLECIMIENTOS_ID
BEFORE INSERT ON ESTABLECIMIENTOS
FOR EACH ROW
BEGIN
    :NEW.ID := SEQ_ESTABLECIMIENTOS.NEXTVAL;
END;
/

-- Trigger de auditoría para COMERCIANTES
CREATE OR REPLACE TRIGGER TRG_COMERCIANTES_AUDIT
BEFORE INSERT OR UPDATE ON COMERCIANTES
FOR EACH ROW
BEGIN
    :NEW.FECHA_ACTUALIZACION := SYSDATE;
    :NEW.USUARIO_ACTUALIZACION := USER;
END;
/

-- Trigger de auditoría para ESTABLECIMIENTOS
CREATE OR REPLACE TRIGGER TRG_ESTABLECIMIENTOS_AUDIT
BEFORE INSERT OR UPDATE ON ESTABLECIMIENTOS
FOR EACH ROW
BEGIN
    :NEW.FECHA_ACTUALIZACION := SYSDATE;
    :NEW.USUARIO_ACTUALIZACION := USER;
END;
/

