-- Archivo: 03_datos_prueba.sql
-- Fecha:  2025/09/05
-- Nota: Se usan datos realistas en lso departamentos como Antioquia, Bogota de otro proyecto de prueba y se colocan varios estado para probar los filtros.

-- Insertar 5 comerciantes
INSERT INTO COMERCIANTES (NOMBRE, DEPARTAMENTO, MUNICIPIO, TELEFONO, CORREO, FECHA_REGISTRO, ESTADO)
VALUES ('Comercio Antioquia SAS', 'Antioquia', 'Medellin', '6041234567', 'info@comercioantioquia.com', SYSDATE - 365, 'ACTIVO');

INSERT INTO COMERCIANTES (NOMBRE, DEPARTAMENTO, MUNICIPIO, TELEFONO, CORREO, FECHA_REGISTRO, ESTADO)
VALUES ('Bogota Traders Ltda', 'Cundinamarca', 'Bogota', '6019876543', 'contacto@bogotatraders.co', SYSDATE - 200, 'INACTIVO');

INSERT INTO COMERCIANTES (NOMBRE, DEPARTAMENTO, MUNICIPIO, TELEFONO, CORREO, FECHA_REGISTRO, ESTADO)
VALUES ('Valle del Cauca Imports', 'Valle del Cauca', 'Cali', '6025551234', 'ventas@valleimports.com', SYSDATE - 100, 'ACTIVO');

INSERT INTO COMERCIANTES (NOMBRE, DEPARTAMENTO, MUNICIPIO, TELEFONO, CORREO, FECHA_REGISTRO, ESTADO)
VALUES ('Atlantico Exports', 'Atlantico', 'Barranquilla', NULL, 'export@atlanticoexp.com', SYSDATE - 50, 'SUSPENDIDO');

INSERT INTO COMERCIANTES (NOMBRE, DEPARTAMENTO, MUNICIPIO, TELEFONO, CORREO, FECHA_REGISTRO, ESTADO)
VALUES ('Santander Retail Group', 'Santander', 'Bucaramanga', '6074445678', NULL, SYSDATE - 10, 'ACTIVO');

-- Insertar 15 establecimientos distribuidos
-- Para comerciante 1
INSERT INTO ESTABLECIMIENTOS (COMERCIANTE_ID, NOMBRE, INGRESOS, NUM_EMPLEADOS)
VALUES (1, 'Sucursal Centro', 1500000.50, 10);

INSERT INTO ESTABLECIMIENTOS (COMERCIANTE_ID, NOMBRE, INGRESOS, NUM_EMPLEADOS)
VALUES (1, 'Sucursal Norte', 1200000.00, 8);

INSERT INTO ESTABLECIMIENTOS (COMERCIANTE_ID, NOMBRE, INGRESOS, NUM_EMPLEADOS)
VALUES (1, 'Sucursal Sur', 1800000.75, 12);

-- Para comerciante 2
INSERT INTO ESTABLECIMIENTOS (COMERCIANTE_ID, NOMBRE, INGRESOS, NUM_EMPLEADOS)
VALUES (2, 'Oficina Principal', 500000.00, 5);

INSERT INTO ESTABLECIMIENTOS (COMERCIANTE_ID, NOMBRE, INGRESOS, NUM_EMPLEADOS)
VALUES (2, 'Almacen Este', 300000.25, 3);

-- Para comerciante 3
INSERT INTO ESTABLECIMIENTOS (COMERCIANTE_ID, NOMBRE, INGRESOS, NUM_EMPLEADOS)
VALUES (3, 'Tienda Cali Centro', 2000000.00, 15);

INSERT INTO ESTABLECIMIENTOS (COMERCIANTE_ID, NOMBRE, INGRESOS, NUM_EMPLEADOS)
VALUES (3, 'Tienda Norte', 1700000.50, 10);

INSERT INTO ESTABLECIMIENTOS (COMERCIANTE_ID, NOMBRE, INGRESOS, NUM_EMPLEADOS)
VALUES (3, 'Tienda Oeste', 1400000.00, 9);

INSERT INTO ESTABLECIMIENTOS (COMERCIANTE_ID, NOMBRE, INGRESOS, NUM_EMPLEADOS)
VALUES (3, 'Tienda Sur', 1600000.75, 11);

-- Para comerciante 4
INSERT INTO ESTABLECIMIENTOS (COMERCIANTE_ID, NOMBRE, INGRESOS, NUM_EMPLEADOS)
VALUES (4, 'Export Hub', 800000.00, 6);

INSERT INTO ESTABLECIMIENTOS (COMERCIANTE_ID, NOMBRE, INGRESOS, NUM_EMPLEADOS)
VALUES (4, 'Deposito Puerto', 600000.50, 4);

-- Para comerciante 5
INSERT INTO ESTABLECIMIENTOS (COMERCIANTE_ID, NOMBRE, INGRESOS, NUM_EMPLEADOS)
VALUES (5, 'Retail Bucara 1', 900000.00, 7);

INSERT INTO ESTABLECIMIENTOS (COMERCIANTE_ID, NOMBRE, INGRESOS, NUM_EMPLEADOS)
VALUES (5, 'Retail Bucara 2', 1100000.25, 8);

INSERT INTO ESTABLECIMIENTOS (COMERCIANTE_ID, NOMBRE, INGRESOS, NUM_EMPLEADOS)
VALUES (5, 'Retail Bucara 3', 1000000.00, 7);

INSERT INTO ESTABLECIMIENTOS (COMERCIANTE_ID, NOMBRE, INGRESOS, NUM_EMPLEADOS)
VALUES (5, 'Retail Bucara 4', 950000.50, 6);

COMMIT;