-- Archivo: 06_funciones_consulta.sql
-- Fecha: 2025/09/05
-- Nota: Usando SYS_REFCURSOR para devoler cursor con la consulta y realizamos filtros dinámicos con LIKE para nombre y municipio.

CREATE OR REPLACE FUNCTION FN_OBTENER_COMERCIANTE(P_ID IN NUMBER)
RETURN SYS_REFCURSOR AS
    V_CURSOR SYS_REFCURSOR;
BEGIN
    OPEN V_CURSOR FOR
    SELECT * FROM COMERCIANTES WHERE ID = P_ID;
    RETURN V_CURSOR;
END;
/

CREATE OR REPLACE FUNCTION FN_LISTAR_COMERCIANTES(
    P_NOMBRE IN VARCHAR2 DEFAULT NULL,
    P_MUNICIPIO IN VARCHAR2 DEFAULT NULL,
    P_ESTADO IN VARCHAR2 DEFAULT NULL
) RETURN SYS_REFCURSOR AS
    V_CURSOR SYS_REFCURSOR;
BEGIN
    OPEN V_CURSOR FOR
    SELECT * FROM COMERCIANTES
    WHERE (P_NOMBRE IS NULL OR UPPER(NOMBRE) LIKE '%' || UPPER(P_NOMBRE) || '%')
      AND (P_MUNICIPIO IS NULL OR UPPER(MUNICIPIO) LIKE '%' || UPPER(P_MUNICIPIO) || '%')
      AND (P_ESTADO IS NULL OR ESTADO = P_ESTADO);
    RETURN V_CURSOR;
END;
/

CREATE OR REPLACE FUNCTION FN_CONTAR_COMERCIANTES
RETURN NUMBER AS
    V_COUNT NUMBER;
BEGIN
    SELECT COUNT(*) INTO V_COUNT FROM COMERCIANTES;
    RETURN V_COUNT;
END;
/
