-- Archivo: 07_crud_establecimientos.sql
-- Fecha:  2025/09/05
-- Nota: Se realiza script similar a comerciantes pero mas simple con validaciones..

CREATE OR REPLACE PROCEDURE SP_CREAR_ESTABLECIMIENTO(
    P_COMERCIANTE_ID IN NUMBER,
    P_NOMBRE IN VARCHAR2,
    P_INGRESOS IN NUMBER,
    P_NUM_EMPLEADOS IN NUMBER,
    P_RESULTADO OUT NUMBER,
    P_MENSAJE OUT VARCHAR2
) AS
BEGIN
    P_RESULTADO := 0;
    P_MENSAJE := 'OK';

    IF P_NOMBRE IS NULL THEN
        P_RESULTADO := -1;
        P_MENSAJE := 'Nombre obligatorio';
        RETURN;
    END IF;

    -- Verificar si comerciante existe
    DECLARE
        V_COUNT NUMBER;
    BEGIN
        SELECT COUNT(*) INTO V_COUNT FROM COMERCIANTES WHERE ID = P_COMERCIANTE_ID;
        IF V_COUNT = 0 THEN
            P_RESULTADO := -1;
            P_MENSAJE := 'Comerciante no existe';
            RETURN;
        END IF;
    END;

    INSERT INTO ESTABLECIMIENTOS (COMERCIANTE_ID, NOMBRE, INGRESOS, NUM_EMPLEADOS)
    VALUES (P_COMERCIANTE_ID, P_NOMBRE, P_INGRESOS, P_NUM_EMPLEADOS);

    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        P_RESULTADO := -1;
        P_MENSAJE := SQLERRM;
        ROLLBACK;
END;
/

CREATE OR REPLACE FUNCTION FN_ESTABLECIMIENTOS_COMERCIANTE(P_COMERCIANTE_ID IN NUMBER)
RETURN SYS_REFCURSOR AS
    V_CURSOR SYS_REFCURSOR;
BEGIN
    OPEN V_CURSOR FOR
    SELECT ID, NOMBRE, INGRESOS, NUM_EMPLEADOS
    FROM ESTABLECIMIENTOS
    WHERE COMERCIANTE_ID = P_COMERCIANTE_ID;

    RETURN V_CURSOR;
END;
/
