-- Archivo: 08_reportes.sql
-- Fecha: 2025/09/05

CREATE OR REPLACE FUNCTION FN_REPORTE_COMERCIANTES_ACTIVOS
RETURN SYS_REFCURSOR AS
    V_CURSOR SYS_REFCURSOR;
BEGIN
    OPEN V_CURSOR FOR
    SELECT NOMBRE, DEPARTAMENTO, MUNICIPIO, TELEFONO, CORREO, FECHA_REGISTRO,
           CANTIDAD_ESTABLECIMIENTOS, TOTAL_INGRESOS, TOTAL_EMPLEADOS
    FROM V_COMERCIANTES_RESUMEN
    WHERE ESTADO = 'ACTIVO'
    ORDER BY CANTIDAD_ESTABLECIMIENTOS DESC;
    RETURN V_CURSOR;
END;
/